server:
  port: 8081
  servlet.session.timeout: 7200
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/desc_trait_media
    username: root
    password: root
    driver-class-name=com: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 120000
      connection-timeout: 30000
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate.ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    servlet.multipart:
      max-file-size: 100MB
      max-request-size: 100MB
    http.encoding:
      force: true
      charset: UTF-8
      enabled: true

  swagger:
    title: App Api Interface Documentation
    version: v1
    base-package: org.big.restapi
    # 是否启用Swagger
    enabled: true
    # 显示请求头
    ui-config.show-request-headers: true
    # 取消使用默认预定义的响应消息,并使用自定义响应消息
    apply-default-response-messages: false
    global-response-message.post[0]:
      code: 200
      message: OK
    global-response-message.post[1]:
      code: 201
      message: 保存成功
    global-response-message.post[2]:
      code: 400
      message: 错误请求
    global-response-message.post[3]:
      code: 401
      message: 令牌错误
    global-response-message.post[4]:
      code: 403
      message: 禁止请求
    global-response-message.post[5]:
      code: 404
      message: 未找到文件
    global-response-message.post[6]:
      code: 413
      message: 请求的实体过大
    global-response-message.post[7]:
      code: 1000
      message: 保存失败
    global-response-message.post[8]:
      code: 500
      message: 服务器异常